### ISSUE TITLE
Include upload size when issuing presigned s3 URLs so it can be enforced

### ISSUE THREAD

**Issue by Gozala** [web3-storage/ucan-protocol#53]
## Overview
I was trying to figure out how to do it other day and have came across these links

https://zaccharles.medium.com/s3-uploads-proxies-vs-presigned-urls-vs-presigned-posts-9661e2b37932
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getSignedUrlPromise-property

However I expect @hugomrdias might already know all about this.

Discussed and identified as action item during [9.6.22 Writes meeting](https://www.notion.so/tues-sep-06-88850b93c13449f9a0c6c247ed5e8837)

**Comment by hugomrdias** [comment]
i think it just needs to be included in the signed querystring but i would need to test it out

**Comment by JeffLowe** [comment]
This need is being tracked in w3up repo in https://github.com/web3-storage/w3up/issues/196
I've moved your notes to the 196 issue so we can track the work alongside all other w3up work.
